{% set name = "xtensor-julia" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/QuantStack/xtensor-julia/archive/{{ version }}.tar.gz
  sha256: 7403d9de2cb76f97c677ab5fc0d5d1999c3c9d9b20e41fc541b0dfbc217779fd

build:
  number: 0
  # Julia and libcxxwrap-julia have not been packaged for conda on Windows
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - xtl >=0.6.2,<0.7
    - xtensor >=0.20.4,<0.21
    - libcxxwrap-julia >=0.5.1,<0.6
  run:
    - {{ pin_compatible('xtl', max_pin='x.x') }}
    - {{ pin_compatible('xtensor', max_pin='x.x') }}

test:
  commands:
    - test -d ${PREFIX}/include/xtensor-julia  # [unix]
    - test -f ${PREFIX}/include/xtensor-julia/jlarray.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xtensor-julia/xtensor-juliaConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xtensor-julia/xtensor-juliaConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xtensor-julia\jlarray.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\xtensor-juliaConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\xtensor-juliaConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net/xtensor
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Julia bindings for the xtensor C++ multi-dimensional array library.'
  description: 'Multi dimensional arrays with broadcasting and lazy computing'
  doc_url: http://xtensor-julia.readthedocs.io
  dev_url: https://github.com/QuantStack/xtensor-julia

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - wolfv
